namespace School_Management_System.Services
{
    internal enum PolicyActionKey
    {
        ENROLLMENT_SUBMIT,
        ENROLLMENT_TRANSFER,
        ENROLLMENT_APPROVE,
        ENROLLMENT_RETURN_FOR_CORRECTION,
        ENROLLMENT_CANCEL,
        ENROLLMENT_DROP,
        ENROLLMENT_SET_STATUS,
        ENROLLMENT_PROMOTE_WAITLIST,
        ARCHIVE_RESTORE,
        MAINTENANCE_BACKUP_EXECUTE,
        MAINTENANCE_RESTORE_EXECUTE,
        MAINTENANCE_YEAR_END_ROLLOVER_EXECUTE
    }
}
