-- School SMS workflow-aligned seed data (MySQL 8)
-- Applies to schema generated by EF migration scripts in Data/Migrations.
-- Active school year is 2026-2027.
-- All seeded students are intentionally unenrolled but remain connected to users,
-- preferred grade levels, curriculum, and requirement workflows.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Reset transactional and workflow data
TRUNCATE TABLE audit_logs;
TRUNCATE TABLE enrollment_state_transitions;
TRUNCATE TABLE governed_operation_logs;
TRUNCATE TABLE exception_queue_items;
TRUNCATE TABLE archive_records;
TRUNCATE TABLE student_requirements;
TRUNCATE TABLE announcements;
TRUNCATE TABLE assessment_scores;
TRUNCATE TABLE assessments;
TRUNCATE TABLE attendance_records;
TRUNCATE TABLE attendance_sessions;
TRUNCATE TABLE student_grades;
TRUNCATE TABLE class_schedules;
TRUNCATE TABLE class_students;
TRUNCATE TABLE enrollments;
TRUNCATE TABLE class_offerings;
TRUNCATE TABLE curriculum_subjects;
TRUNCATE TABLE sections;
TRUNCATE TABLE students;
TRUNCATE TABLE teachers;
TRUNCATE TABLE users;

-- Reset master data used by workflows
TRUNCATE TABLE subjects;
TRUNCATE TABLE curricula;
TRUNCATE TABLE school_settings;
TRUNCATE TABLE grading_periods;
TRUNCATE TABLE grade_components;
TRUNCATE TABLE school_years;
TRUNCATE TABLE grade_levels;
TRUNCATE TABLE rooms;
TRUNCATE TABLE time_slots;

SET FOREIGN_KEY_CHECKS = 1;

-- ------------------------------------------------------------
-- 1) Master setup
-- ------------------------------------------------------------

INSERT INTO grade_levels (code, name, created_at, updated_at) VALUES
('G7', 'Grade 7', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('G8', 'Grade 8', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('G9', 'Grade 9', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('G10', 'Grade 10', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

INSERT INTO school_years (name, start_date, end_date, status, created_at, updated_at) VALUES
('2028-2029', '2028-06-01', '2029-03-31', 'PLANNING', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('2027-2028', '2027-06-01', '2028-03-31', 'PLANNING', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('2026-2027', '2026-06-01', '2027-03-31', 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('2025-2026', '2025-06-01', '2026-03-31', 'CLOSED', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

INSERT INTO school_settings (
    school_name, school_code, school_address, principal_name, grading_setup,
    enrollment_configuration, enrollment_open_date, enrollment_close_date,
    print_header_line1, print_header_line2, student_number_prefix, next_student_number,
    default_section_capacity, default_grade_level_ids, created_at, updated_at
)
VALUES (
    'School Management System', 'SMS-001', 'Main Campus, City', 'Dr. Elena Ramos', 'K-12 quarter system (WW 30%, PT 50%, QA 20%)',
    'Approval Required', '2026-04-01', '2026-08-31',
    'School Management System', 'Enrollment Services Office', 'STU', 1046,
    45, NULL, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
);

INSERT INTO grade_components (name, weight, is_active, created_at, updated_at) VALUES
('WRITTEN_WORKS', 0.3000, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('PERFORMANCE_TASKS', 0.5000, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('QUARTERLY_ASSESSMENT', 0.2000, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

INSERT INTO rooms (code, name, capacity, is_active, created_at, updated_at) VALUES
('RM-201', 'JHS Room 201', 45, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('RM-202', 'JHS Room 202', 45, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('SCI-1', 'Science Lab 1', 40, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('COMP-1', 'Computer Lab 1', 40, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

INSERT INTO time_slots (code, name, start_time, end_time, is_bell_period, sort_order, created_at, updated_at) VALUES
('P1', 'Period 1', '07:30:00', '08:30:00', 1, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('P2', 'Period 2', '08:30:00', '09:30:00', 1, 2, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('P3', 'Period 3', '09:45:00', '10:45:00', 1, 3, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('P4', 'Period 4', '10:45:00', '11:45:00', 1, 4, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('P5', 'Period 5', '13:00:00', '14:00:00', 1, 5, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('P6', 'Period 6', '14:00:00', '15:00:00', 1, 6, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

SET @g7 := (SELECT Id FROM grade_levels WHERE code = 'G7' LIMIT 1);
SET @g8 := (SELECT Id FROM grade_levels WHERE code = 'G8' LIMIT 1);
SET @g9 := (SELECT Id FROM grade_levels WHERE code = 'G9' LIMIT 1);
SET @g10 := (SELECT Id FROM grade_levels WHERE code = 'G10' LIMIT 1);
SET @sy_active := (SELECT Id FROM school_years WHERE name = '2026-2027' LIMIT 1);

-- ------------------------------------------------------------
-- 2) Accounts and profiles
-- ------------------------------------------------------------
-- Hash notes:
-- admin password: admin
-- teacher01..03 password: Teacher@123
-- student01..45 password: Student@123

INSERT INTO users (username, password_hash, role, can_login, status, created_at, updated_at) VALUES
('admin',    'PBKDF2$100000$qwxNiDThP2h6++xyQUViAw==$sKWUg5Cj4I8oHZwyntKa+7ptKJ9gPyBBepQAUxZxhX8=', 'SUPERADMIN', 1, 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('teacher01','PBKDF2$100000$rD+Ll3iiEapB9K3KmhMmBQ==$fV14yOaVKW7U0YOPMGh3KZ+3oDlSpYkNA5F2P7iZD/w=', 'TEACHER',    0, 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('teacher02','PBKDF2$100000$rD+Ll3iiEapB9K3KmhMmBQ==$fV14yOaVKW7U0YOPMGh3KZ+3oDlSpYkNA5F2P7iZD/w=', 'TEACHER',    0, 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('teacher03','PBKDF2$100000$rD+Ll3iiEapB9K3KmhMmBQ==$fV14yOaVKW7U0YOPMGh3KZ+3oDlSpYkNA5F2P7iZD/w=', 'TEACHER',    0, 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

INSERT INTO users (username, password_hash, role, can_login, status, created_at, updated_at)
SELECT
    CONCAT('student', LPAD(seq.n, 2, '0')),
    'PBKDF2$100000$IRvX5mR9j9olgVaU93KO2w==$a7LptMcDUL71RMOpFVv4vU1bWu0vt6Pj3/HaYl/egMo=',
    'STUDENT',
    0,
    CASE
        WHEN seq.n = 8 THEN 'LOCKED'
        WHEN seq.n = 10 THEN 'INACTIVE'
        ELSE 'ACTIVE'
    END,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT @rownum_users := @rownum_users + 1 AS n
    FROM information_schema.COLUMNS, (SELECT @rownum_users := 0) init_users
    LIMIT 45
) AS seq;

INSERT INTO teachers (user_id, employee_no, first_name, last_name, middle_name, email, contact_no, specialization, advisory_assignment_status, employment_status, hire_date, status, created_at, updated_at)
SELECT Id, 'T-1001', 'Ana',  'Dela Cruz', NULL, 'ana.delacruz@school.local',  '09170000001', 'English',     'ASSIGNED',   'REGULAR', '2021-06-01', 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6) FROM users WHERE username = 'teacher01';
INSERT INTO teachers (user_id, employee_no, first_name, last_name, middle_name, email, contact_no, specialization, advisory_assignment_status, employment_status, hire_date, status, created_at, updated_at)
SELECT Id, 'T-1002', 'Ben',  'Santos',    NULL, 'ben.santos@school.local',   '09170000002', 'Mathematics', 'ASSIGNED',   'REGULAR', '2020-06-01', 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6) FROM users WHERE username = 'teacher02';
INSERT INTO teachers (user_id, employee_no, first_name, last_name, middle_name, email, contact_no, specialization, advisory_assignment_status, employment_status, hire_date, status, created_at, updated_at)
SELECT Id, 'T-1003', 'Cara', 'Reyes',     NULL, 'cara.reyes@school.local',   '09170000003', 'Science',     'UNASSIGNED', 'REGULAR', '2019-06-01', 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6) FROM users WHERE username = 'teacher03';

-- ------------------------------------------------------------
-- 3) Academic setup and student preferences
-- ------------------------------------------------------------

INSERT INTO curricula (name, description, is_active, created_at, updated_at)
VALUES ('JHS Core Curriculum', 'Core subjects for Grades 7-10', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

SET @cur := (SELECT Id FROM curricula WHERE name = 'JHS Core Curriculum' LIMIT 1);

INSERT INTO subjects (code, title, description, grade_level_id, is_active, created_at, updated_at) VALUES
('ENG7',  'English 7',      'Grade 7 English',       @g7, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('MATH7', 'Mathematics 7',  'Grade 7 Mathematics',   @g7, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('SCI7',  'Science 7',      'Grade 7 Science',       @g7, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('FIL7',  'Filipino 7',     'Grade 7 Filipino',      @g7, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('ENG8',  'English 8',      'Grade 8 English',       @g8, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('MATH8', 'Mathematics 8',  'Grade 8 Mathematics',   @g8, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('SCI8',  'Science 8',      'Grade 8 Science',       @g8, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('FIL8',  'Filipino 8',     'Grade 8 Filipino',      @g8, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('ENG9',  'English 9',      'Grade 9 English',       @g9, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('MATH9', 'Mathematics 9',  'Grade 9 Mathematics',   @g9, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('SCI9',  'Science 9',      'Grade 9 Science',       @g9, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('FIL9',  'Filipino 9',     'Grade 9 Filipino',      @g9, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('ENG10', 'English 10',     'Grade 10 English',      @g10, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('MATH10','Mathematics 10', 'Grade 10 Mathematics',  @g10, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('SCI10', 'Science 10',     'Grade 10 Science',      @g10, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('FIL10', 'Filipino 10',    'Grade 10 Filipino',     @g10, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

INSERT INTO curriculum_subjects (curriculum_id, grade_level_id, subject_id, semester, is_required, sort_order, created_at, updated_at)
SELECT @cur, s.grade_level_id, s.Id, 1, 1, ROW_NUMBER() OVER (PARTITION BY s.grade_level_id ORDER BY s.code), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
FROM subjects s;

INSERT INTO students (
    user_id, lrn, student_number, first_name, last_name, middle_name, birthdate, age, sex,
    address, contact_no, guardian_name, guardian_contact, previous_school,
    preferred_grade_level_id, preferred_curriculum_id, status, created_at, updated_at
)
SELECT
    u.Id,
    CONCAT('LRN-', LPAD(seq.n, 4, '0')),
    CONCAT('STU-', LPAD(1000 + seq.n, 4, '0')),
    names.first_name,
    names.last_name,
    names.middle_name,
    DATE_ADD('2011-06-01', INTERVAL seq.n DAY),
    13 + MOD(seq.n, 4),
    CASE WHEN MOD(seq.n, 2) = 0 THEN 'F' ELSE 'M' END,
    CONCAT('Purok ', seq.n),
    CONCAT('0918', LPAD(seq.n, 7, '0')),
    names.guardian_name,
    CONCAT('0999', LPAD(seq.n, 7, '0')),
    CASE WHEN MOD(seq.n, 6) = 0 THEN CONCAT('Previous School ', LPAD(seq.n, 2, '0')) ELSE NULL END,
    CASE
        WHEN seq.n BETWEEN 1 AND 12 THEN @g7
        WHEN seq.n BETWEEN 13 AND 23 THEN @g8
        WHEN seq.n BETWEEN 24 AND 34 THEN @g9
        ELSE @g10
    END,
    @cur,
    CASE
        WHEN seq.n = 8 THEN 'LOCKED'
        WHEN seq.n = 10 THEN 'INACTIVE'
        ELSE 'ACTIVE'
    END,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT @rownum_students := @rownum_students + 1 AS n
    FROM information_schema.COLUMNS, (SELECT @rownum_students := 0) init_students
    LIMIT 45
) AS seq
JOIN users u ON u.username = CONCAT('student', LPAD(seq.n, 2, '0'))
JOIN (
    SELECT 1 AS n, 'Alyssa' AS first_name, 'Fernandez' AS last_name, 'Lopez' AS middle_name, 'Marites Fernandez' AS guardian_name
    UNION ALL SELECT 2, 'Joshua', 'Mendoza', 'Reyes', 'Arnel Mendoza'
    UNION ALL SELECT 3, 'Bea', 'Santos', 'Cruz', 'Lorna Santos'
    UNION ALL SELECT 4, 'Carl', 'Navarro', 'Diaz', 'Edna Navarro'
    UNION ALL SELECT 5, 'Danica', 'Torres', 'Garcia', 'Rogelio Torres'
    UNION ALL SELECT 6, 'Ethan', 'Villanueva', 'Perez', 'Mylene Villanueva'
    UNION ALL SELECT 7, 'Faith', 'Aquino', 'Ramos', 'Glenda Aquino'
    UNION ALL SELECT 8, 'Gabriel', 'Castillo', 'Morales', 'Victor Castillo'
    UNION ALL SELECT 9, 'Hannah', 'Domingo', 'Flores', 'Cecilia Domingo'
    UNION ALL SELECT 10, 'Ivan', 'Gutierrez', 'Silva', 'Nelson Gutierrez'
    UNION ALL SELECT 11, 'Jasmine', 'Herrera', 'Bautista', 'Aileen Herrera'
    UNION ALL SELECT 12, 'Kyle', 'Ignacio', 'Torres', 'Ramon Ignacio'
    UNION ALL SELECT 13, 'Lara', 'Jimenez', 'Castro', 'Melanie Jimenez'
    UNION ALL SELECT 14, 'Miguel', 'Lazaro', 'Molina', 'Dennis Lazaro'
    UNION ALL SELECT 15, 'Nica', 'Marquez', 'Santos', 'Rosalie Marquez'
    UNION ALL SELECT 16, 'Owen', 'Natividad', 'Lim', 'Emelyn Natividad'
    UNION ALL SELECT 17, 'Patricia', 'Ortega', 'Salazar', 'Joel Ortega'
    UNION ALL SELECT 18, 'Quinn', 'Pascual', 'Rivera', 'Leah Pascual'
    UNION ALL SELECT 19, 'Rica', 'Quinto', 'Valdez', 'Alfred Quinto'
    UNION ALL SELECT 20, 'Sean', 'Rosales', 'Mendoza', 'Janice Rosales'
    UNION ALL SELECT 21, 'Trisha', 'Samonte', 'Aquino', 'Mario Samonte'
    UNION ALL SELECT 22, 'Ulysses', 'Tolentino', 'Reyes', 'Jocelyn Tolentino'
    UNION ALL SELECT 23, 'Vanessa', 'Umali', 'Soriano', 'Nestor Umali'
    UNION ALL SELECT 24, 'Warren', 'Valencia', 'Dela Cruz', 'Olivia Valencia'
    UNION ALL SELECT 25, 'Xyra', 'Zamora', 'Torres', 'Hector Zamora'
    UNION ALL SELECT 26, 'Adrian', 'Alcantara', 'Neri', 'Vilma Alcantara'
    UNION ALL SELECT 27, 'Bianca', 'Baltazar', 'Ocampo', 'Ruben Baltazar'
    UNION ALL SELECT 28, 'Cedric', 'Caballero', 'Padilla', 'Sheryl Caballero'
    UNION ALL SELECT 29, 'Denise', 'De Leon', 'Ramos', 'Tomas De Leon'
    UNION ALL SELECT 30, 'Enzo', 'Estrella', 'Sarmiento', 'Lilibeth Estrella'
    UNION ALL SELECT 31, 'Frances', 'Fajardo', 'Tan', 'Erwin Fajardo'
    UNION ALL SELECT 32, 'Gian', 'Galang', 'Uy', 'Maricel Galang'
    UNION ALL SELECT 33, 'Hazel', 'Hilario', 'Villanueva', 'Arturo Hilario'
    UNION ALL SELECT 34, 'Isabel', 'Inocencio', 'Yap', 'Cristina Inocencio'
    UNION ALL SELECT 35, 'Jerome', 'Kalaw', 'Zulueta', 'Perla Kalaw'
    UNION ALL SELECT 36, 'Krisha', 'Labrador', 'Aguilar', 'Bobby Labrador'
    UNION ALL SELECT 37, 'Lance', 'Malabanan', 'Bonifacio', 'Irene Malabanan'
    UNION ALL SELECT 38, 'Mara', 'Nepomuceno', 'Chua', 'Teodoro Nepomuceno'
    UNION ALL SELECT 39, 'Noel', 'Olivarez', 'David', 'Marissa Olivarez'
    UNION ALL SELECT 40, 'Paula', 'Pineda', 'Evangelista', 'Sergio Pineda'
    UNION ALL SELECT 41, 'Ralph', 'Querubin', 'Francisco', 'Nilda Querubin'
    UNION ALL SELECT 42, 'Sofia', 'Roxas', 'Gonzales', 'Dominador Roxas'
    UNION ALL SELECT 43, 'Theo', 'Sy', 'Hernandez', 'Mona Sy'
    UNION ALL SELECT 44, 'Yasmin', 'Tan', 'Ilagan', 'Felix Tan'
    UNION ALL SELECT 45, 'Zach', 'Villareal', 'Javier', 'Carla Villareal'
) AS names ON names.n = seq.n;

SET @t1 := (SELECT Id FROM teachers WHERE employee_no = 'T-1001' LIMIT 1);
SET @t2 := (SELECT Id FROM teachers WHERE employee_no = 'T-1002' LIMIT 1);
SET @t3 := (SELECT Id FROM teachers WHERE employee_no = 'T-1003' LIMIT 1);

INSERT INTO sections (school_year_id, grade_level_id, name, capacity, adviser_teacher_id, created_at, updated_at) VALUES
(@sy_active, @g7,  'Emerald',  45, @t1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g7,  'Sapphire', 45, @t2, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g8,  'Topaz',    45, @t3, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g8,  'Ruby',     45, @t1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g9,  'Quartz',   45, @t2, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g9,  'Opal',     45, @t3, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g10, 'Onyx',     45, @t1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g10, 'Jade',     45, @t2, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

SET @sec7a := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Emerald' LIMIT 1);
SET @sec7b := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Sapphire' LIMIT 1);
SET @sec8a := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Topaz' LIMIT 1);
SET @sec8b := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Ruby' LIMIT 1);
SET @sec9a := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Quartz' LIMIT 1);
SET @sec9b := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Opal' LIMIT 1);
SET @sec10a := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Onyx' LIMIT 1);
SET @sec10b := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Jade' LIMIT 1);

SET @sub_eng7 := (SELECT Id FROM subjects WHERE code = 'ENG7' LIMIT 1);
SET @sub_math7 := (SELECT Id FROM subjects WHERE code = 'MATH7' LIMIT 1);
SET @sub_sci7 := (SELECT Id FROM subjects WHERE code = 'SCI7' LIMIT 1);
SET @sub_eng8 := (SELECT Id FROM subjects WHERE code = 'ENG8' LIMIT 1);
SET @sub_math8 := (SELECT Id FROM subjects WHERE code = 'MATH8' LIMIT 1);
SET @sub_sci8 := (SELECT Id FROM subjects WHERE code = 'SCI8' LIMIT 1);
SET @sub_eng9 := (SELECT Id FROM subjects WHERE code = 'ENG9' LIMIT 1);
SET @sub_math9 := (SELECT Id FROM subjects WHERE code = 'MATH9' LIMIT 1);
SET @sub_sci9 := (SELECT Id FROM subjects WHERE code = 'SCI9' LIMIT 1);
SET @sub_eng10 := (SELECT Id FROM subjects WHERE code = 'ENG10' LIMIT 1);
SET @sub_math10 := (SELECT Id FROM subjects WHERE code = 'MATH10' LIMIT 1);
SET @sub_sci10 := (SELECT Id FROM subjects WHERE code = 'SCI10' LIMIT 1);

INSERT INTO class_offerings (school_year_id, section_id, subject_id, teacher_id, curriculum_id, status, room, created_at, updated_at)
SELECT
    @sy_active,
    seq.section_id,
    seq.subject_id,
    CASE MOD(seq.rn - 1, 3)
        WHEN 0 THEN @t1
        WHEN 1 THEN @t2
        ELSE @t3
    END,
    @cur,
    CASE WHEN seq.rn <= 8 THEN 'FINALIZED' ELSE 'ACTIVE' END,
    CASE MOD(seq.rn - 1, 4)
        WHEN 0 THEN 'RM-201'
        WHEN 1 THEN 'RM-202'
        WHEN 2 THEN 'SCI-1'
        ELSE 'COMP-1'
    END,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT
        sec.Id AS section_id,
        cs.subject_id,
        ROW_NUMBER() OVER (ORDER BY sec.Id, subj.code) AS rn
    FROM sections sec
    JOIN curriculum_subjects cs
        ON cs.curriculum_id = @cur
       AND cs.grade_level_id = sec.grade_level_id
    JOIN subjects subj ON subj.Id = cs.subject_id
    WHERE sec.school_year_id = @sy_active
) AS seq;

-- Schedules for active year offerings only
SET @rm201 := (SELECT Id FROM rooms WHERE code = 'RM-201' LIMIT 1);
SET @rm202 := (SELECT Id FROM rooms WHERE code = 'RM-202' LIMIT 1);
SET @scilab := (SELECT Id FROM rooms WHERE code = 'SCI-1' LIMIT 1);
SET @complab := (SELECT Id FROM rooms WHERE code = 'COMP-1' LIMIT 1);
SET @p1 := (SELECT Id FROM time_slots WHERE code = 'P1' LIMIT 1);
SET @p2 := (SELECT Id FROM time_slots WHERE code = 'P2' LIMIT 1);
SET @p3 := (SELECT Id FROM time_slots WHERE code = 'P3' LIMIT 1);
SET @p4 := (SELECT Id FROM time_slots WHERE code = 'P4' LIMIT 1);
SET @p5 := (SELECT Id FROM time_slots WHERE code = 'P5' LIMIT 1);
SET @p6 := (SELECT Id FROM time_slots WHERE code = 'P6' LIMIT 1);

SET @off_eng7_emerald := (SELECT Id FROM class_offerings WHERE school_year_id = @sy_active AND section_id = @sec7a AND subject_id = @sub_eng7 LIMIT 1);
SET @off_math7_sapphire := (SELECT Id FROM class_offerings WHERE school_year_id = @sy_active AND section_id = @sec7b AND subject_id = @sub_math7 LIMIT 1);
SET @off_sci8_topaz := (SELECT Id FROM class_offerings WHERE school_year_id = @sy_active AND section_id = @sec8a AND subject_id = @sub_sci8 LIMIT 1);

INSERT INTO class_schedules (class_offering_id, room_id, time_slot_id, day_of_week, start_time, end_time, created_at, updated_at)
SELECT
    seq.class_offering_id,
    CASE MOD(seq.rn - 1, 4)
        WHEN 0 THEN @rm201
        WHEN 1 THEN @rm202
        WHEN 2 THEN @scilab
        ELSE @complab
    END,
    ts.Id,
    1 + MOD(seq.rn - 1, 5),
    ts.start_time,
    ts.end_time,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT
        co.Id AS class_offering_id,
        ROW_NUMBER() OVER (ORDER BY co.section_id, co.subject_id, co.Id) AS rn
    FROM class_offerings co
    WHERE co.school_year_id = @sy_active
) AS seq
JOIN time_slots ts ON ts.Id = CASE MOD(seq.rn - 1, 6)
    WHEN 0 THEN @p1
    WHEN 1 THEN @p2
    WHEN 2 THEN @p3
    WHEN 3 THEN @p4
    WHEN 4 THEN @p5
    ELSE @p6
END;

-- ------------------------------------------------------------
-- 4) Unenrolled admissions data, grading windows, attendance templates
-- ------------------------------------------------------------

INSERT INTO grading_periods (school_year_id, name, start_date, end_date, status, created_at, updated_at) VALUES
(@sy_active, 'Q1', '2026-06-10', '2026-08-15', 'OPEN',     UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, 'Q2', '2026-08-20', '2026-10-15', 'UPCOMING', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, 'Q3', '2026-10-20', '2026-12-15', 'UPCOMING', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, 'Q4', '2027-01-05', '2027-03-15', 'UPCOMING', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

SET @q1 := (SELECT Id FROM grading_periods WHERE school_year_id = @sy_active AND name = 'Q1' LIMIT 1);
SET @q2 := (SELECT Id FROM grading_periods WHERE school_year_id = @sy_active AND name = 'Q2' LIMIT 1);

INSERT INTO assessments (class_offering_id, grading_period_id, component_id, title, max_score, date_given, created_at, updated_at)
SELECT
    seq.class_offering_id,
    @q1,
    gc.Id,
    CONCAT('Q1 ', REPLACE(gc.name, '_', ' '), ' - ', seq.subject_code),
    CASE gc.name
        WHEN 'WRITTEN_WORKS' THEN 50.00
        WHEN 'PERFORMANCE_TASKS' THEN 100.00
        ELSE 60.00
    END,
    DATE_ADD('2026-07-01', INTERVAL (seq.rn - 1) DAY),
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT
        co.Id AS class_offering_id,
        subj.code AS subject_code,
        ROW_NUMBER() OVER (ORDER BY co.section_id, co.subject_id, co.Id) AS rn
    FROM class_offerings co
    JOIN subjects subj ON subj.Id = co.subject_id
    WHERE co.school_year_id = @sy_active
) AS seq
JOIN grade_components gc ON gc.is_active = 1;

INSERT INTO assessments (class_offering_id, grading_period_id, component_id, title, max_score, date_given, created_at, updated_at)
SELECT
    seq.class_offering_id,
    @q2,
    gc.Id,
    CONCAT('Q2 ', REPLACE(gc.name, '_', ' '), ' - ', seq.subject_code),
    CASE gc.name
        WHEN 'WRITTEN_WORKS' THEN 40.00
        WHEN 'PERFORMANCE_TASKS' THEN 100.00
        ELSE 60.00
    END,
    DATE_ADD('2026-09-01', INTERVAL (seq.rn - 1) DAY),
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT
        co.Id AS class_offering_id,
        subj.code AS subject_code,
        ROW_NUMBER() OVER (ORDER BY co.section_id, co.subject_id, co.Id) AS rn
    FROM class_offerings co
    JOIN subjects subj ON subj.Id = co.subject_id
    WHERE co.school_year_id = @sy_active
) AS seq
JOIN grade_components gc ON gc.is_active = 1
WHERE seq.rn <= 8;

INSERT INTO attendance_sessions (class_offering_id, session_date, created_at, updated_at)
SELECT Id, DATE_SUB(CURDATE(), INTERVAL 3 DAY), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6) FROM class_offerings WHERE school_year_id = @sy_active
UNION ALL
SELECT Id, DATE_SUB(CURDATE(), INTERVAL 2 DAY), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6) FROM class_offerings WHERE school_year_id = @sy_active
UNION ALL
SELECT Id, DATE_SUB(CURDATE(), INTERVAL 1 DAY), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6) FROM class_offerings WHERE school_year_id = @sy_active;

-- ------------------------------------------------------------
-- 5) Announcements, requirements, archives, audit trail
-- ------------------------------------------------------------

SET @admin_uid := (SELECT Id FROM users WHERE username = 'admin' LIMIT 1);
SET @teacher1_uid := (SELECT Id FROM users WHERE username = 'teacher01' LIMIT 1);
SET @teacher2_uid := (SELECT Id FROM users WHERE username = 'teacher02' LIMIT 1);

INSERT INTO announcements (posted_by_user_id, title, body, audience_type, section_id, class_offering_id, posted_at, created_at, updated_at)
VALUES
(@admin_uid,    'Welcome Back', 'School year 2026-2027 is active. Enrollment intake is open and section schedules are prepared.', 'ALL', NULL, NULL, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@admin_uid,    'Grade 7 Advisory Meeting', 'Grade 7 advisory parent meeting this Friday at 3:00 PM.', 'SECTION', @sec7a, NULL, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@teacher1_uid, 'English Activity Reminder', 'Bring your notebook and reading materials for tomorrow''s class.', 'OFFERING', NULL, @off_eng7_emerald, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@teacher2_uid, 'Math Practice Set', 'Answer the uploaded drill before Friday.', 'OFFERING', NULL, @off_math7_sapphire, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

INSERT INTO student_requirements (student_id, requirement_name, is_submitted, submitted_at, notes, verified_by_user_id, created_at, updated_at)
SELECT
    seeded.student_id,
    seeded.requirement_name,
    seeded.is_submitted,
    CASE
        WHEN seeded.is_submitted = 1 THEN DATE_SUB(UTC_TIMESTAMP(6), INTERVAL MOD(seeded.student_id + seeded.order_no, 12) DAY)
        ELSE NULL
    END,
    CASE
        WHEN seeded.requirement_name = 'Birth Certificate' AND seeded.is_submitted = 1 THEN 'Verified during admission review'
        WHEN seeded.is_submitted = 1 THEN 'Submitted before enrollment approval'
        ELSE 'Pending submission'
    END,
    CASE
        WHEN seeded.is_submitted = 1 THEN @admin_uid
        ELSE NULL
    END,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT
        s.Id AS student_id,
        req.order_no,
        req.requirement_name,
        CASE req.requirement_name
            WHEN 'Birth Certificate' THEN 1
            WHEN 'Good Moral Certificate' THEN CASE WHEN MOD(s.Id, 4) = 0 THEN 0 ELSE 1 END
            ELSE CASE WHEN MOD(s.Id, 5) IN (0, 1) THEN 0 ELSE 1 END
        END AS is_submitted
    FROM students s
    CROSS JOIN (
        SELECT 1 AS order_no, 'Birth Certificate' AS requirement_name
        UNION ALL
        SELECT 2 AS order_no, 'Good Moral Certificate' AS requirement_name
        UNION ALL
        SELECT 3 AS order_no, 'Form 137' AS requirement_name
    ) AS req
) AS seeded;

INSERT INTO archive_records (entity_type, original_entity_id, payload, deleted_by_user_id, deleted_at, is_restored, restored_by_user_id, restored_at, notes)
VALUES
('students', (SELECT Id FROM students WHERE lrn = 'LRN-0010' LIMIT 1), '{"lrn":"LRN-0010","state":"UNENROLLED","reason":"archive workflow demo"}', @admin_uid, UTC_TIMESTAMP(6), 0, NULL, NULL, 'SOFT_DELETE');

INSERT INTO audit_logs (user_id, action, entity, entity_id, payload, created_at)
VALUES
(@admin_uid, 'SEED',   'database',       NULL,                                                '{"message":"Connected unenrolled seed executed"}', UTC_TIMESTAMP(6)),
(@admin_uid, 'CREATE', 'school_settings', (SELECT Id FROM school_settings ORDER BY Id DESC LIMIT 1), '{"school":"School Management System","next_student_number":1046}', UTC_TIMESTAMP(6)),
(@admin_uid, 'CREATE', 'school_years',   @sy_active,                                           '{"name":"2026-2027","status":"ACTIVE"}', UTC_TIMESTAMP(6)),
(@admin_uid, 'CREATE', 'students',       (SELECT Id FROM students WHERE lrn = 'LRN-0001' LIMIT 1),  '{"lrn":"LRN-0001","preferred_grade":"G7","enrollment_state":"UNENROLLED"}', UTC_TIMESTAMP(6)),
(@teacher1_uid, 'UPDATE', 'class_offerings', @off_eng7_emerald,                               '{"note":"seeded class offering finalized"}', UTC_TIMESTAMP(6));

-- ------------------------------------------------------------
-- 6) Structural governance data (connected, non-enrollment dependent)
-- ------------------------------------------------------------

SET @seed_corr_admissions := 'SEED-CORR-ADM-0001';
SET @seed_corr_restore := 'SEED-CORR-MNT-0001';
SET @seed_archive_student10 := (SELECT Id FROM archive_records ORDER BY Id DESC LIMIT 1);
SET @seed_student_0001 := (SELECT Id FROM students WHERE lrn = 'LRN-0001' LIMIT 1);
SET @seed_student_0044 := (SELECT Id FROM students WHERE lrn = 'LRN-0044' LIMIT 1);

INSERT INTO governed_operation_logs (
    correlation_id,
    policy_key,
    action,
    entity,
    entity_id,
    status,
    message,
    payload,
    actor_user_id,
    created_at
)
VALUES
(@seed_corr_admissions, 'ADMISSIONS_REQUIREMENT_REVIEW', 'ADMISSIONS_REQUIREMENT_REVIEW_START',   'students',        @seed_student_0001,  'STARTED',   'Seeded admissions review started.',             '{"student_lrn":"LRN-0001","school_year":"2026-2027"}', @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 10 DAY)),
(@seed_corr_admissions, 'ADMISSIONS_REQUIREMENT_REVIEW', 'ADMISSIONS_REQUIREMENT_REVIEW_COMPLETE', 'students',        @seed_student_0044,  'SUCCEEDED', 'Seeded admissions review completed.',           '{"student_lrn":"LRN-0044","requirements":"COMPLETE"}', @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 8 DAY)),
(@seed_corr_restore,    'MAINTENANCE_RESTORE_EXECUTE',   'RESTORE_BLOCKED',                        'archive_records', @seed_archive_student10, 'BLOCKED', 'Seeded restore preflight block sample.', '{"reason":"relationship dependencies"}', @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 1 DAY));

INSERT INTO exception_queue_items (
    category,
    source_module,
    entity,
    entity_id,
    severity,
    status,
    summary,
    details,
    correlation_id,
    assignment_status,
    assigned_to_user_id,
    acknowledged_by_user_id,
    acknowledged_at,
    resolved_by_user_id,
    resolved_at,
    occurrence_count,
    last_occurred_at,
    created_by_user_id,
    created_at,
    updated_at
)
VALUES
('DEPENDENCY_BLOCK',    'Archive.Restore',        'archive_records', @seed_archive_student10, 'WARNING', 'OPEN',     'Seeded archive dependency block sample.',   'Review linked student artifacts before restore.', @seed_corr_restore,    'UNASSIGNED', NULL, NULL, NULL, NULL, NULL, 1, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 12 HOUR), @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 12 HOUR), DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 12 HOUR)),
('REQUIREMENT_REVIEW',  'Admissions.Requirements','students',        @seed_student_0044,      'INFO',    'RESOLVED', 'Seeded admissions review completion sample.', 'All requirements verified for seeded student.',   @seed_corr_admissions, 'RESOLVED',  @admin_uid, @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 7 DAY), @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 7 DAY), 1, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 7 DAY), @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 8 DAY), DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 7 DAY));

SELECT 'Seed complete (connected, active 2026-2027, all students unenrolled)' AS status;
