-- School SMS workflow-aligned seed data (MySQL 8)
-- Applies to schema generated by EF migration scripts in Data/Migrations.
-- Includes data for admin, teacher, student, and structural governance workflows.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Reset transactional and workflow data
TRUNCATE TABLE audit_logs;
TRUNCATE TABLE enrollment_state_transitions;
TRUNCATE TABLE governed_operation_logs;
TRUNCATE TABLE exception_queue_items;
TRUNCATE TABLE archive_records;
TRUNCATE TABLE student_requirements;
TRUNCATE TABLE announcements;
TRUNCATE TABLE assessment_scores;
TRUNCATE TABLE assessments;
TRUNCATE TABLE attendance_records;
TRUNCATE TABLE attendance_sessions;
TRUNCATE TABLE student_grades;
TRUNCATE TABLE class_schedules;
TRUNCATE TABLE class_students;
TRUNCATE TABLE enrollments;
TRUNCATE TABLE class_offerings;
TRUNCATE TABLE curriculum_subjects;
TRUNCATE TABLE sections;
TRUNCATE TABLE students;
TRUNCATE TABLE teachers;
TRUNCATE TABLE users;

-- Reset master data used by workflows
TRUNCATE TABLE subjects;
TRUNCATE TABLE curricula;
TRUNCATE TABLE school_settings;
TRUNCATE TABLE grading_periods;
TRUNCATE TABLE grade_components;
TRUNCATE TABLE school_years;
TRUNCATE TABLE grade_levels;
TRUNCATE TABLE rooms;
TRUNCATE TABLE time_slots;

SET FOREIGN_KEY_CHECKS = 1;

-- ------------------------------------------------------------
-- 1) Master setup
-- ------------------------------------------------------------

INSERT INTO grade_levels (code, name, created_at, updated_at) VALUES
('G7', 'Grade 7', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('G8', 'Grade 8', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('G9', 'Grade 9', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('G10', 'Grade 10', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

INSERT INTO school_years (name, start_date, end_date, status, created_at, updated_at) VALUES
('2026-2027', '2026-06-01', '2027-03-31', 'PLANNING', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('2025-2026', '2025-06-01', '2026-03-31', 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('2024-2025', '2024-06-01', '2025-03-31', 'CLOSED', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

INSERT INTO school_settings (
    school_name, school_code, school_address, principal_name, grading_setup,
    enrollment_configuration, enrollment_open_date, enrollment_close_date,
    print_header_line1, print_header_line2, student_number_prefix, next_student_number,
    default_section_capacity, default_grade_level_ids, created_at, updated_at
)
VALUES (
    'School Management System', 'SMS-001', 'Main Campus, City', 'Dr. Elena Ramos', 'K-12 quarter system (WW 30%, PT 50%, QA 20%)',
    'Approval Required', '2025-04-01', '2025-06-30',
    'School Management System', 'Enrollment Services Office', 'STU', 1001,
    45, NULL, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
);

INSERT INTO grade_components (name, weight, is_active, created_at, updated_at) VALUES
('WRITTEN_WORKS', 0.3000, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('PERFORMANCE_TASKS', 0.5000, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('QUARTERLY_ASSESSMENT', 0.2000, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

INSERT INTO rooms (code, name, capacity, is_active, created_at, updated_at) VALUES
('RM-201', 'JHS Room 201', 45, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('RM-202', 'JHS Room 202', 45, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('SCI-1', 'Science Lab 1', 40, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('COMP-1', 'Computer Lab 1', 40, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

INSERT INTO time_slots (code, name, start_time, end_time, is_bell_period, sort_order, created_at, updated_at) VALUES
('P1', 'Period 1', '07:30:00', '08:30:00', 1, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('P2', 'Period 2', '08:30:00', '09:30:00', 1, 2, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('P3', 'Period 3', '09:45:00', '10:45:00', 1, 3, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('P4', 'Period 4', '10:45:00', '11:45:00', 1, 4, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('P5', 'Period 5', '13:00:00', '14:00:00', 1, 5, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('P6', 'Period 6', '14:00:00', '15:00:00', 1, 6, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

-- ------------------------------------------------------------
-- 2) Accounts and profiles
-- ------------------------------------------------------------
-- Hash notes:
-- admin password: admin
-- teacher01..03 password: Teacher@123
-- student01..40 password: Student@123

INSERT INTO users (username, password_hash, role, can_login, status, created_at, updated_at) VALUES
('admin',    'PBKDF2$100000$qwxNiDThP2h6++xyQUViAw==$sKWUg5Cj4I8oHZwyntKa+7ptKJ9gPyBBepQAUxZxhX8=', 'SUPERADMIN', 1, 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('teacher01','PBKDF2$100000$rD+Ll3iiEapB9K3KmhMmBQ==$fV14yOaVKW7U0YOPMGh3KZ+3oDlSpYkNA5F2P7iZD/w=', 'TEACHER',    0, 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('teacher02','PBKDF2$100000$rD+Ll3iiEapB9K3KmhMmBQ==$fV14yOaVKW7U0YOPMGh3KZ+3oDlSpYkNA5F2P7iZD/w=', 'TEACHER',    0, 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('teacher03','PBKDF2$100000$rD+Ll3iiEapB9K3KmhMmBQ==$fV14yOaVKW7U0YOPMGh3KZ+3oDlSpYkNA5F2P7iZD/w=', 'TEACHER',    0, 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

INSERT INTO users (username, password_hash, role, can_login, status, created_at, updated_at)
SELECT
    CONCAT('student', LPAD(seq.n, 2, '0')),
    'PBKDF2$100000$IRvX5mR9j9olgVaU93KO2w==$a7LptMcDUL71RMOpFVv4vU1bWu0vt6Pj3/HaYl/egMo=',
    'STUDENT',
    0,
    CASE
        WHEN seq.n = 8 THEN 'LOCKED'
        WHEN seq.n = 10 THEN 'INACTIVE'
        ELSE 'ACTIVE'
    END,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT @rownum_users := @rownum_users + 1 AS n
    FROM information_schema.COLUMNS, (SELECT @rownum_users := 0) init_users
    LIMIT 40
) AS seq;

INSERT INTO teachers (user_id, employee_no, first_name, last_name, middle_name, email, contact_no, specialization, advisory_assignment_status, employment_status, hire_date, status, created_at, updated_at)
SELECT Id, 'T-1001', 'Ana',  'Dela Cruz', NULL, 'ana.delacruz@school.local',  '09170000001', 'English',     'ASSIGNED',   'REGULAR', '2021-06-01', 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6) FROM users WHERE username = 'teacher01';
INSERT INTO teachers (user_id, employee_no, first_name, last_name, middle_name, email, contact_no, specialization, advisory_assignment_status, employment_status, hire_date, status, created_at, updated_at)
SELECT Id, 'T-1002', 'Ben',  'Santos',    NULL, 'ben.santos@school.local',   '09170000002', 'Mathematics', 'ASSIGNED',   'REGULAR', '2020-06-01', 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6) FROM users WHERE username = 'teacher02';
INSERT INTO teachers (user_id, employee_no, first_name, last_name, middle_name, email, contact_no, specialization, advisory_assignment_status, employment_status, hire_date, status, created_at, updated_at)
SELECT Id, 'T-1003', 'Cara', 'Reyes',     NULL, 'cara.reyes@school.local',   '09170000003', 'Science',     'UNASSIGNED', 'REGULAR', '2019-06-01', 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6) FROM users WHERE username = 'teacher03';

INSERT INTO students (user_id, lrn, student_number, first_name, last_name, middle_name, birthdate, age, sex, address, contact_no, guardian_name, guardian_contact, previous_school, status, created_at, updated_at)
SELECT
    u.Id,
    CONCAT('LRN-', LPAD(seq.n, 4, '0')),
    CONCAT('STU-', LPAD(1000 + seq.n, 4, '0')),
    CONCAT('Student', LPAD(seq.n, 2, '0')),
    CONCAT('Learner', LPAD(seq.n, 2, '0')),
    NULL,
    DATE_ADD('2011-06-01', INTERVAL seq.n DAY),
    13 + MOD(seq.n, 4),
    CASE WHEN MOD(seq.n, 2) = 0 THEN 'F' ELSE 'M' END,
    CONCAT('Purok ', seq.n),
    CONCAT('0918', LPAD(seq.n, 7, '0')),
    CONCAT('Guardian ', LPAD(seq.n, 2, '0')),
    CONCAT('0999', LPAD(seq.n, 7, '0')),
    CASE WHEN MOD(seq.n, 6) = 0 THEN CONCAT('Previous School ', LPAD(seq.n, 2, '0')) ELSE NULL END,
    CASE
        WHEN seq.n = 8 THEN 'LOCKED'
        WHEN seq.n = 10 THEN 'INACTIVE'
        ELSE 'ACTIVE'
    END,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT @rownum_students := @rownum_students + 1 AS n
    FROM information_schema.COLUMNS, (SELECT @rownum_students := 0) init_students
    LIMIT 40
) AS seq
JOIN users u ON u.username = CONCAT('student', LPAD(seq.n, 2, '0'));

-- ------------------------------------------------------------
-- 3) Academic setup
-- ------------------------------------------------------------

INSERT INTO curricula (name, description, is_active, created_at, updated_at)
VALUES ('JHS Core Curriculum', 'Core subjects for Grades 7-10', 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

SET @g7 := (SELECT Id FROM grade_levels WHERE code = 'G7' LIMIT 1);
SET @g8 := (SELECT Id FROM grade_levels WHERE code = 'G8' LIMIT 1);
SET @g9 := (SELECT Id FROM grade_levels WHERE code = 'G9' LIMIT 1);
SET @g10 := (SELECT Id FROM grade_levels WHERE code = 'G10' LIMIT 1);

INSERT INTO subjects (code, title, description, grade_level_id, is_active, created_at, updated_at) VALUES
('ENG7',  'English 7',     'Grade 7 English',     @g7, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('MATH7', 'Mathematics 7', 'Grade 7 Mathematics', @g7, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('SCI7',  'Science 7',     'Grade 7 Science',     @g7, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('FIL7',  'Filipino 7',    'Grade 7 Filipino',    @g7, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('ENG8',  'English 8',     'Grade 8 English',     @g8, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('MATH8', 'Mathematics 8', 'Grade 8 Mathematics', @g8, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('SCI8',  'Science 8',     'Grade 8 Science',     @g8, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('FIL8',  'Filipino 8',    'Grade 8 Filipino',    @g8, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('ENG9',  'English 9',     'Grade 9 English',     @g9, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('MATH9', 'Mathematics 9', 'Grade 9 Mathematics', @g9, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('ENG10',  'English 10',     'Grade 10 English',     @g10, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('MATH10', 'Mathematics 10', 'Grade 10 Mathematics', @g10, 1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

SET @cur := (SELECT Id FROM curricula WHERE name = 'JHS Core Curriculum' LIMIT 1);
INSERT INTO curriculum_subjects (curriculum_id, grade_level_id, subject_id, semester, is_required, sort_order, created_at, updated_at)
SELECT @cur, s.grade_level_id, s.Id, 1, 1, ROW_NUMBER() OVER (PARTITION BY s.grade_level_id ORDER BY s.code), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
FROM subjects s;

SET @sy_active := (SELECT Id FROM school_years WHERE name = '2025-2026' LIMIT 1);

SET @t1 := (SELECT Id FROM teachers WHERE employee_no = 'T-1001' LIMIT 1);
SET @t2 := (SELECT Id FROM teachers WHERE employee_no = 'T-1002' LIMIT 1);
SET @t3 := (SELECT Id FROM teachers WHERE employee_no = 'T-1003' LIMIT 1);

INSERT INTO sections (school_year_id, grade_level_id, name, capacity, adviser_teacher_id, created_at, updated_at) VALUES
(@sy_active, @g7, 'Emerald', 45, @t1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g7, 'Sapphire', 45, @t2, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g8, 'Topaz', 45, @t3, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g8, 'Ruby', 45, @t1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g9, 'Quartz', 45, @t2, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g9, 'Opal', 45, @t3, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g10, 'Onyx', 45, @t1, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, @g10, 'Jade', 45, @t2, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

SET @sec7a := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Emerald' LIMIT 1);
SET @sec7b := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Sapphire' LIMIT 1);
SET @sec8a := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Topaz' LIMIT 1);
SET @sec8b := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Ruby' LIMIT 1);
SET @sec9a := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Quartz' LIMIT 1);
SET @sec9b := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Opal' LIMIT 1);
SET @sec10a := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Onyx' LIMIT 1);
SET @sec10b := (SELECT Id FROM sections WHERE school_year_id = @sy_active AND name = 'Jade' LIMIT 1);

SET @sub_eng7 := (SELECT Id FROM subjects WHERE code = 'ENG7' LIMIT 1);
SET @sub_math7 := (SELECT Id FROM subjects WHERE code = 'MATH7' LIMIT 1);
SET @sub_sci7 := (SELECT Id FROM subjects WHERE code = 'SCI7' LIMIT 1);
SET @sub_eng8 := (SELECT Id FROM subjects WHERE code = 'ENG8' LIMIT 1);
SET @sub_math8 := (SELECT Id FROM subjects WHERE code = 'MATH8' LIMIT 1);
SET @sub_sci8 := (SELECT Id FROM subjects WHERE code = 'SCI8' LIMIT 1);
SET @sub_eng9 := (SELECT Id FROM subjects WHERE code = 'ENG9' LIMIT 1);
SET @sub_math9 := (SELECT Id FROM subjects WHERE code = 'MATH9' LIMIT 1);
SET @sub_eng10 := (SELECT Id FROM subjects WHERE code = 'ENG10' LIMIT 1);
SET @sub_math10 := (SELECT Id FROM subjects WHERE code = 'MATH10' LIMIT 1);

INSERT INTO class_offerings (school_year_id, section_id, subject_id, teacher_id, curriculum_id, status, room, created_at, updated_at)
SELECT
    @sy_active,
    seq.section_id,
    seq.subject_id,
    CASE MOD(seq.rn - 1, 3)
        WHEN 0 THEN @t1
        WHEN 1 THEN @t2
        ELSE @t3
    END AS teacher_id,
    @cur,
    CASE WHEN seq.rn <= 6 THEN 'FINALIZED' ELSE 'ACTIVE' END AS status,
    CASE MOD(seq.rn - 1, 4)
        WHEN 0 THEN 'RM-201'
        WHEN 1 THEN 'RM-202'
        WHEN 2 THEN 'SCI-1'
        ELSE 'COMP-1'
    END AS room,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT
        sec.Id AS section_id,
        cs.subject_id,
        ROW_NUMBER() OVER (ORDER BY sec.Id, subj.code) AS rn
    FROM sections sec
    JOIN curriculum_subjects cs
        ON cs.curriculum_id = @cur
       AND cs.grade_level_id = sec.grade_level_id
    JOIN subjects subj ON subj.Id = cs.subject_id
    WHERE sec.school_year_id = @sy_active
) AS seq;

-- Schedules for active year offerings only
SET @rm201 := (SELECT Id FROM rooms WHERE code = 'RM-201' LIMIT 1);
SET @rm202 := (SELECT Id FROM rooms WHERE code = 'RM-202' LIMIT 1);
SET @scilab := (SELECT Id FROM rooms WHERE code = 'SCI-1' LIMIT 1);
SET @complab := (SELECT Id FROM rooms WHERE code = 'COMP-1' LIMIT 1);
SET @p1 := (SELECT Id FROM time_slots WHERE code = 'P1' LIMIT 1);
SET @p2 := (SELECT Id FROM time_slots WHERE code = 'P2' LIMIT 1);
SET @p3 := (SELECT Id FROM time_slots WHERE code = 'P3' LIMIT 1);
SET @p4 := (SELECT Id FROM time_slots WHERE code = 'P4' LIMIT 1);
SET @p5 := (SELECT Id FROM time_slots WHERE code = 'P5' LIMIT 1);
SET @p6 := (SELECT Id FROM time_slots WHERE code = 'P6' LIMIT 1);

SET @off_eng7_emerald := (SELECT Id FROM class_offerings WHERE school_year_id = @sy_active AND section_id = @sec7a AND subject_id = @sub_eng7 LIMIT 1);
INSERT INTO class_schedules (class_offering_id, room_id, time_slot_id, day_of_week, start_time, end_time, created_at, updated_at)
SELECT
    seq.class_offering_id,
    CASE MOD(seq.rn - 1, 4)
        WHEN 0 THEN @rm201
        WHEN 1 THEN @rm202
        WHEN 2 THEN @scilab
        ELSE @complab
    END AS room_id,
    ts.Id AS time_slot_id,
    1 + MOD(seq.rn - 1, 5) AS day_of_week,
    ts.start_time,
    ts.end_time,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT
        co.Id AS class_offering_id,
        ROW_NUMBER() OVER (ORDER BY co.section_id, co.subject_id, co.Id) AS rn
    FROM class_offerings co
    WHERE co.school_year_id = @sy_active
) AS seq
JOIN time_slots ts ON ts.Id = CASE MOD(seq.rn - 1, 6)
    WHEN 0 THEN @p1
    WHEN 1 THEN @p2
    WHEN 2 THEN @p3
    WHEN 3 THEN @p4
    WHEN 4 THEN @p5
    ELSE @p6
END;

-- ------------------------------------------------------------
-- 4) Enrollment, class roster, grading, attendance
-- ------------------------------------------------------------

INSERT INTO enrollments (school_year_id, student_id, grade_level_id, section_id, curriculum_id, status, approval_status, enrollment_type, enrolled_at, created_at, updated_at)
SELECT @sy_active, s.Id, @g7, @sec7a, @cur, 'ENROLLED', 'APPROVED', 'NEW', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
FROM students s WHERE s.lrn BETWEEN 'LRN-0001' AND 'LRN-0005';

INSERT INTO enrollments (school_year_id, student_id, grade_level_id, section_id, curriculum_id, status, approval_status, enrollment_type, enrolled_at, created_at, updated_at)
SELECT @sy_active, s.Id, @g7, @sec7b, @cur, 'ENROLLED', 'APPROVED', 'NEW', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
FROM students s WHERE s.lrn BETWEEN 'LRN-0006' AND 'LRN-0010';

INSERT INTO enrollments (school_year_id, student_id, grade_level_id, section_id, curriculum_id, status, approval_status, enrollment_type, enrolled_at, created_at, updated_at)
SELECT @sy_active, s.Id, @g8, @sec8a, @cur, 'ENROLLED', 'APPROVED', 'NEW', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
FROM students s WHERE s.lrn BETWEEN 'LRN-0011' AND 'LRN-0015';

INSERT INTO enrollments (school_year_id, student_id, grade_level_id, section_id, curriculum_id, status, approval_status, enrollment_type, enrolled_at, created_at, updated_at)
SELECT @sy_active, s.Id, @g8, @sec8b, @cur, 'ENROLLED', 'APPROVED', 'NEW', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
FROM students s WHERE s.lrn BETWEEN 'LRN-0016' AND 'LRN-0020';

INSERT INTO enrollments (school_year_id, student_id, grade_level_id, section_id, curriculum_id, status, approval_status, enrollment_type, enrolled_at, created_at, updated_at)
SELECT @sy_active, s.Id, @g9, @sec9a, @cur, 'ENROLLED', 'APPROVED', 'NEW', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
FROM students s WHERE s.lrn BETWEEN 'LRN-0021' AND 'LRN-0025';

INSERT INTO enrollments (school_year_id, student_id, grade_level_id, section_id, curriculum_id, status, approval_status, enrollment_type, enrolled_at, created_at, updated_at)
SELECT @sy_active, s.Id, @g9, @sec9b, @cur, 'ENROLLED', 'APPROVED', 'NEW', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
FROM students s WHERE s.lrn BETWEEN 'LRN-0026' AND 'LRN-0030';

INSERT INTO enrollments (school_year_id, student_id, grade_level_id, section_id, curriculum_id, status, approval_status, enrollment_type, enrolled_at, created_at, updated_at)
SELECT @sy_active, s.Id, @g10, @sec10a, @cur, 'ENROLLED', 'APPROVED', 'NEW', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
FROM students s WHERE s.lrn BETWEEN 'LRN-0031' AND 'LRN-0035';

INSERT INTO enrollments (school_year_id, student_id, grade_level_id, section_id, curriculum_id, status, approval_status, enrollment_type, enrolled_at, created_at, updated_at)
SELECT @sy_active, s.Id, @g10, @sec10b, @cur, 'ENROLLED', 'APPROVED', 'NEW', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
FROM students s WHERE s.lrn BETWEEN 'LRN-0036' AND 'LRN-0040';

INSERT INTO class_students (class_offering_id, student_id, enrollment_id, status, created_at, updated_at)
SELECT o.Id, e.student_id, e.Id, 'ACTIVE', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
FROM enrollments e
JOIN class_offerings o ON o.section_id = e.section_id AND o.school_year_id = e.school_year_id
WHERE e.status = 'ENROLLED';

-- Keep a few non-active cases for enrollment and roster workflows
UPDATE enrollments e
JOIN students s ON s.Id = e.student_id
SET
    e.status = CASE
        WHEN s.lrn IN ('LRN-0010', 'LRN-0029') THEN 'DROPPED'
        WHEN s.lrn IN ('LRN-0039') THEN 'TRANSFERRED_OUT'
        ELSE e.status
    END,
    e.updated_at = UTC_TIMESTAMP(6)
WHERE e.school_year_id = @sy_active
  AND s.lrn IN ('LRN-0010', 'LRN-0029', 'LRN-0039');

UPDATE class_students cs
JOIN enrollments e ON e.Id = cs.enrollment_id
SET
    cs.status = IF(e.status = 'ENROLLED', 'ACTIVE', 'DROPPED'),
    cs.updated_at = UTC_TIMESTAMP(6)
WHERE e.school_year_id = @sy_active;

INSERT INTO grading_periods (school_year_id, name, start_date, end_date, status, created_at, updated_at) VALUES
(@sy_active, 'Q1', '2025-06-10', '2025-08-15', 'POSTED', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, 'Q2', '2025-08-20', '2025-10-15', 'OPEN',   UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, 'Q3', '2025-10-20', '2025-12-15', 'CLOSED', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@sy_active, 'Q4', '2026-01-05', '2026-03-15', 'CLOSED', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

SET @q1 := (SELECT Id FROM grading_periods WHERE school_year_id = @sy_active AND name = 'Q1' LIMIT 1);
SET @q2 := (SELECT Id FROM grading_periods WHERE school_year_id = @sy_active AND name = 'Q2' LIMIT 1);
SET @ww_component_id := (SELECT Id FROM grade_components WHERE name = 'WRITTEN_WORKS' LIMIT 1);
SET @pt_component_id := (SELECT Id FROM grade_components WHERE name = 'PERFORMANCE_TASKS' LIMIT 1);
SET @qa_component_id := (SELECT Id FROM grade_components WHERE name = 'QUARTERLY_ASSESSMENT' LIMIT 1);
SET @wt_ww := (SELECT weight FROM grade_components WHERE Id = @ww_component_id LIMIT 1);
SET @wt_pt := (SELECT weight FROM grade_components WHERE Id = @pt_component_id LIMIT 1);
SET @wt_qa := (SELECT weight FROM grade_components WHERE Id = @qa_component_id LIMIT 1);

-- Q1: full assessment setup for all active-year offerings (all components)
INSERT INTO assessments (class_offering_id, grading_period_id, component_id, title, max_score, date_given, created_at, updated_at)
SELECT
    seq.class_offering_id,
    @q1,
    gc.Id,
    CONCAT('Q1 ', REPLACE(gc.name, '_', ' '), ' - ', seq.subject_code),
    CASE gc.name
        WHEN 'WRITTEN_WORKS' THEN 50.00
        WHEN 'PERFORMANCE_TASKS' THEN 100.00
        ELSE 60.00
    END AS max_score,
    DATE_ADD('2025-07-01', INTERVAL (seq.rn - 1) DAY),
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT
        co.Id AS class_offering_id,
        subj.code AS subject_code,
        ROW_NUMBER() OVER (ORDER BY co.section_id, co.subject_id, co.Id) AS rn
    FROM class_offerings co
    JOIN subjects subj ON subj.Id = co.subject_id
    WHERE co.school_year_id = @sy_active
) AS seq
JOIN grade_components gc ON gc.is_active = 1;

-- Q2: partial assessment setup (first 8 offerings) for realistic in-progress grading
INSERT INTO assessments (class_offering_id, grading_period_id, component_id, title, max_score, date_given, created_at, updated_at)
SELECT
    seq.class_offering_id,
    @q2,
    gc.Id,
    CONCAT('Q2 ', REPLACE(gc.name, '_', ' '), ' - ', seq.subject_code),
    CASE gc.name
        WHEN 'WRITTEN_WORKS' THEN 40.00
        WHEN 'PERFORMANCE_TASKS' THEN 100.00
        ELSE 60.00
    END AS max_score,
    DATE_ADD('2025-09-01', INTERVAL (seq.rn - 1) DAY),
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT
        co.Id AS class_offering_id,
        subj.code AS subject_code,
        ROW_NUMBER() OVER (ORDER BY co.section_id, co.subject_id, co.Id) AS rn
    FROM class_offerings co
    JOIN subjects subj ON subj.Id = co.subject_id
    WHERE co.school_year_id = @sy_active
) AS seq
JOIN grade_components gc ON gc.is_active = 1
WHERE seq.rn <= 8;

-- Scores linked to every assessment/student relationship in the roster
INSERT INTO assessment_scores (assessment_id, student_id, score, created_at, updated_at)
SELECT
    a.Id,
    cs.student_id,
    ROUND(a.max_score * (0.72 + (MOD(cs.student_id + a.Id, 23) / 100)), 2) AS score,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM assessments a
JOIN class_students cs ON cs.class_offering_id = a.class_offering_id
WHERE a.grading_period_id = @q1;

INSERT INTO assessment_scores (assessment_id, student_id, score, created_at, updated_at)
SELECT
    a.Id,
    cs.student_id,
    ROUND(a.max_score * (0.78 + (MOD(cs.student_id + a.Id, 17) / 100)), 2) AS score,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM assessments a
JOIN class_students cs ON cs.class_offering_id = a.class_offering_id
WHERE a.grading_period_id = @q2
  AND cs.status = 'ACTIVE';

-- Grades are derived from assessment scores for each class/student/quarter
INSERT INTO student_grades (class_offering_id, grading_period_id, student_id, written_works, performance_tasks, quarterly_assessment, quarter_grade, submitted_at, created_at, updated_at)
SELECT
    component_rollup.class_offering_id,
    component_rollup.grading_period_id,
    component_rollup.student_id,
    ROUND(MAX(CASE WHEN component_rollup.component_name = 'WRITTEN_WORKS' THEN component_rollup.component_grade END), 2) AS written_works,
    ROUND(MAX(CASE WHEN component_rollup.component_name = 'PERFORMANCE_TASKS' THEN component_rollup.component_grade END), 2) AS performance_tasks,
    ROUND(MAX(CASE WHEN component_rollup.component_name = 'QUARTERLY_ASSESSMENT' THEN component_rollup.component_grade END), 2) AS quarterly_assessment,
    ROUND(
        COALESCE(MAX(CASE WHEN component_rollup.component_name = 'WRITTEN_WORKS' THEN component_rollup.component_grade END), 0) * @wt_ww
      + COALESCE(MAX(CASE WHEN component_rollup.component_name = 'PERFORMANCE_TASKS' THEN component_rollup.component_grade END), 0) * @wt_pt
      + COALESCE(MAX(CASE WHEN component_rollup.component_name = 'QUARTERLY_ASSESSMENT' THEN component_rollup.component_grade END), 0) * @wt_qa,
        2
    ) AS quarter_grade,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT
        a.class_offering_id,
        a.grading_period_id,
        sc.student_id,
        gc.name AS component_name,
        ROUND((AVG(sc.score) / NULLIF(MAX(a.max_score), 0)) * 100, 2) AS component_grade
    FROM assessments a
    JOIN grade_components gc ON gc.Id = a.component_id
    JOIN assessment_scores sc ON sc.assessment_id = a.Id
    GROUP BY a.class_offering_id, a.grading_period_id, sc.student_id, gc.name
) AS component_rollup
GROUP BY component_rollup.class_offering_id, component_rollup.grading_period_id, component_rollup.student_id;

INSERT INTO attendance_sessions (class_offering_id, session_date, created_at, updated_at)
SELECT Id, DATE_SUB(CURDATE(), INTERVAL 3 DAY), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6) FROM class_offerings WHERE school_year_id = @sy_active
UNION ALL
SELECT Id, DATE_SUB(CURDATE(), INTERVAL 2 DAY), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6) FROM class_offerings WHERE school_year_id = @sy_active
UNION ALL
SELECT Id, DATE_SUB(CURDATE(), INTERVAL 1 DAY), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6) FROM class_offerings WHERE school_year_id = @sy_active;

SET @admin_uid := (SELECT Id FROM users WHERE username = 'admin' LIMIT 1);
INSERT INTO attendance_records (attendance_session_id, student_id, marked_by_user_id, status, reason, created_at, updated_at)
SELECT s.Id, cs.student_id, @admin_uid,
       CASE
           WHEN (cs.student_id + DAY(s.session_date)) % 11 = 0 THEN 'ABSENT'
           WHEN (cs.student_id + DAY(s.session_date)) % 7 = 0 THEN 'LATE'
           ELSE 'PRESENT'
       END,
       CASE
           WHEN (cs.student_id + DAY(s.session_date)) % 11 = 0 THEN 'Sick'
           WHEN (cs.student_id + DAY(s.session_date)) % 7 = 0 THEN 'Transport delay'
           ELSE NULL
       END,
       UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)
FROM attendance_sessions s
JOIN class_students cs ON cs.class_offering_id = s.class_offering_id
WHERE cs.status = 'ACTIVE';

-- ------------------------------------------------------------
-- 5) Announcements, requirements, archives, audit trail
-- ------------------------------------------------------------

SET @teacher1_uid := (SELECT Id FROM users WHERE username = 'teacher01' LIMIT 1);
SET @teacher2_uid := (SELECT Id FROM users WHERE username = 'teacher02' LIMIT 1);

INSERT INTO announcements (posted_by_user_id, title, body, audience_type, section_id, class_offering_id, posted_at, created_at, updated_at)
VALUES
(@admin_uid,   'Welcome Back', 'Classes are now active. Please monitor attendance and requirements.', 'ALL', NULL, NULL, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@admin_uid,   'Grade 7 Advisory Meeting', 'Grade 7 advisory parent meeting this Friday at 3:00 PM.', 'SECTION', @sec7a, NULL, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@teacher1_uid,'English Activity Reminder', 'Bring your notebook and reading materials for tomorrow''s class.', 'OFFERING', NULL, @off_eng7_emerald, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(@teacher2_uid,'Math Practice Set', 'Answer the uploaded drill before Friday.', 'SECTION', @sec7b, NULL, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

-- Student requirements workflow data
INSERT INTO student_requirements (student_id, requirement_name, is_submitted, submitted_at, notes, verified_by_user_id, created_at, updated_at)
SELECT
    seeded.student_id,
    seeded.requirement_name,
    seeded.is_submitted,
    CASE
        WHEN seeded.is_submitted = 1 THEN DATE_SUB(UTC_TIMESTAMP(6), INTERVAL MOD(seeded.student_id + seeded.order_no, 12) DAY)
        ELSE NULL
    END AS submitted_at,
    CASE
        WHEN seeded.requirement_name = 'Birth Certificate' THEN 'Verified during enrollment'
        WHEN seeded.is_submitted = 1 THEN 'Submitted'
        ELSE 'Pending submission'
    END AS notes,
    @admin_uid,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
FROM (
    SELECT
        s.Id AS student_id,
        req.order_no,
        req.requirement_name,
        CASE req.requirement_name
            WHEN 'Birth Certificate' THEN 1
            WHEN 'Good Moral Certificate' THEN CASE WHEN MOD(s.Id, 4) = 0 THEN 0 ELSE 1 END
            ELSE CASE WHEN MOD(s.Id, 5) IN (0, 1) THEN 0 ELSE 1 END
        END AS is_submitted
    FROM students s
    CROSS JOIN (
        SELECT 1 AS order_no, 'Birth Certificate' AS requirement_name
        UNION ALL
        SELECT 2 AS order_no, 'Good Moral Certificate' AS requirement_name
        UNION ALL
        SELECT 3 AS order_no, 'Form 137' AS requirement_name
    ) AS req
) AS seeded;

-- Archive workflow sample record
INSERT INTO archive_records (entity_type, original_entity_id, payload, deleted_by_user_id, deleted_at, is_restored, restored_by_user_id, restored_at, notes)
VALUES
('students', (SELECT Id FROM students WHERE lrn = 'LRN-0010' LIMIT 1), '{"lrn":"LRN-0010","reason":"soft delete demo"}', @admin_uid, UTC_TIMESTAMP(6), 0, NULL, NULL, 'SOFT_DELETE');

-- Minimal audit data for dashboard and activity history
INSERT INTO audit_logs (user_id, action, entity, entity_id, payload, created_at)
VALUES
(@admin_uid, 'SEED', 'database', NULL, '{"message":"Workflow-aligned seed executed"}', UTC_TIMESTAMP(6)),
(@admin_uid, 'CREATE', 'school_settings', (SELECT Id FROM school_settings ORDER BY Id DESC LIMIT 1), '{"school":"School Management System"}', UTC_TIMESTAMP(6)),
(@admin_uid, 'CREATE', 'school_years', @sy_active, '{"name":"2025-2026"}', UTC_TIMESTAMP(6)),
(@admin_uid, 'CREATE', 'enrollments', NULL, '{"note":"bulk enroll seed"}', UTC_TIMESTAMP(6)),
(@teacher1_uid, 'UPDATE', 'student_grades', NULL, '{"note":"seed teacher grade update"}', UTC_TIMESTAMP(6));

-- ------------------------------------------------------------
-- 6) Structural governance data (SR-01..SR-06)
-- ------------------------------------------------------------

SET @seed_corr_submit := 'SEED-CORR-ENR-0001';
SET @seed_corr_drop := 'SEED-CORR-ENR-0002';
SET @seed_corr_transfer := 'SEED-CORR-ENR-0003';
SET @seed_corr_restore := 'SEED-CORR-MNT-0001';

SET @seed_enr_0001 := (
    SELECT e.Id
    FROM enrollments e
    JOIN students s ON s.Id = e.student_id
    WHERE e.school_year_id = @sy_active AND s.lrn = 'LRN-0001'
    LIMIT 1
);
SET @seed_enr_0010 := (
    SELECT e.Id
    FROM enrollments e
    JOIN students s ON s.Id = e.student_id
    WHERE e.school_year_id = @sy_active AND s.lrn = 'LRN-0010'
    LIMIT 1
);
SET @seed_enr_0039 := (
    SELECT e.Id
    FROM enrollments e
    JOIN students s ON s.Id = e.student_id
    WHERE e.school_year_id = @sy_active AND s.lrn = 'LRN-0039'
    LIMIT 1
);

INSERT INTO enrollment_state_transitions (
    enrollment_id,
    previous_status,
    new_status,
    previous_approval_status,
    new_approval_status,
    trigger_action,
    reason_code,
    reason_text,
    performed_by_user_id,
    correlation_id,
    metadata_json,
    created_at
)
VALUES
(@seed_enr_0001, NULL,        'PENDING',        NULL,       'PENDING',  'SUBMIT_REQUEST', 'SUBMIT_REQUEST', 'Seeded submit request.',           @admin_uid, @seed_corr_submit,   '{"source":"seed","stage":"submit"}',   DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 10 DAY)),
(@seed_enr_0001, 'PENDING',   'ENROLLED',       'PENDING',  'APPROVED', 'APPROVE',        'APPROVE',        'Seeded approval decision.',       @admin_uid, @seed_corr_submit,   '{"source":"seed","stage":"approve"}',  DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 9 DAY)),
(@seed_enr_0010, 'ENROLLED',  'DROPPED',        'APPROVED', 'REJECTED', 'SET_STATUS',     'DROP',           'Seeded drop status transition.',  @admin_uid, @seed_corr_drop,     '{"source":"seed","stage":"drop"}',     DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 4 DAY)),
(@seed_enr_0039, 'ENROLLED',  'TRANSFERRED_OUT','APPROVED', 'APPROVED', 'SET_STATUS',     'TRANSFER_OUT',   'Seeded transfer-out transition.', @admin_uid, @seed_corr_transfer, '{"source":"seed","stage":"transfer"}', DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 2 DAY));

INSERT INTO governed_operation_logs (
    correlation_id,
    policy_key,
    action,
    entity,
    entity_id,
    status,
    message,
    payload,
    actor_user_id,
    created_at
)
VALUES
(@seed_corr_submit,   'ENROLLMENT_SUBMIT',            'ENROLLMENT_SUBMIT_START',   'enrollments', @seed_enr_0001, 'STARTED',   'Seeded enrollment submit started.',    '{"student_lrn":"LRN-0001"}', @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 10 DAY)),
(@seed_corr_submit,   'ENROLLMENT_APPROVE',           'ENROLLMENT_APPROVE_SUCCESS', 'enrollments', @seed_enr_0001, 'SUCCEEDED', 'Seeded enrollment approval succeeded.', '{"new_status":"ENROLLED"}',  @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 9 DAY)),
(@seed_corr_restore,  'MAINTENANCE_RESTORE_EXECUTE',  'RESTORE_BLOCKED',            'database_backup_restore', NULL, 'BLOCKED', 'Seeded restore preflight block sample.', '{"reason":"compatibility"}', @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 1 DAY));

INSERT INTO exception_queue_items (
    category,
    source_module,
    entity,
    entity_id,
    severity,
    status,
    summary,
    details,
    correlation_id,
    assignment_status,
    assigned_to_user_id,
    acknowledged_by_user_id,
    acknowledged_at,
    resolved_by_user_id,
    resolved_at,
    occurrence_count,
    last_occurred_at,
    created_by_user_id,
    created_at,
    updated_at
)
VALUES
('DEPENDENCY_BLOCK',  'Archive.Restore',          'archive_records', (SELECT Id FROM archive_records ORDER BY Id DESC LIMIT 1), 'WARNING', 'OPEN',     'Seeded archive dependency block sample.',  'Review dependencies before restore.', @seed_corr_restore, 'UNASSIGNED', NULL, NULL, NULL, NULL, NULL, 1, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 12 HOUR), @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 12 HOUR), DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 12 HOUR)),
('CONCURRENCY_CONFLICT','Enrollment.ReviewWorkbench','enrollments',   @seed_enr_0010,                                        'WARNING', 'RESOLVED', 'Seeded stale enrollment concurrency sample.','Resolved during review refresh.',       @seed_corr_drop,    'RESOLVED',  @admin_uid, @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 8 HOUR), @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 6 HOUR), 2, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 6 HOUR), @admin_uid, DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 8 HOUR), DATE_SUB(UTC_TIMESTAMP(6), INTERVAL 6 HOUR));

SELECT 'Seed complete (workflow + structural governance aligned)' AS status;

