// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School_Management_System.Data;

#nullable disable

namespace School_Management_System.Data.EfMigrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305154000_20260305_ModelBaseline")]
    partial class _20260305_ModelBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("School_Management_System.Models.Announcement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AudienceType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("audience_type");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<long?>("ClassOfferingId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_offering_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("posted_at");

                    b.Property<long>("PostedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("posted_by_user_id");

                    b.Property<long?>("SectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("section_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassOfferingId");

                    b.HasIndex("PostedByUserId");

                    b.HasIndex("SectionId");

                    b.ToTable("announcements");
                });

            modelBuilder.Entity("School_Management_System.Models.Assessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClassOfferingId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_offering_id");

                    b.Property<long>("ComponentId")
                        .HasColumnType("bigint")
                        .HasColumnName("component_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateGiven")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_given");

                    b.Property<long>("GradingPeriodId")
                        .HasColumnType("bigint")
                        .HasColumnName("grading_period_id");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("max_score");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassOfferingId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("GradingPeriodId");

                    b.ToTable("assessments");
                });

            modelBuilder.Entity("School_Management_System.Models.AssessmentScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AssessmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assessment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("score");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("assessment_scores");
                });

            modelBuilder.Entity("School_Management_System.Models.AttendanceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AttendanceSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("attendance_session_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long?>("MarkedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("marked_by_user_id");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceSessionId");

                    b.HasIndex("MarkedByUserId");

                    b.HasIndex("StudentId");

                    b.ToTable("attendance_records");
                });

            modelBuilder.Entity("School_Management_System.Models.AttendanceSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClassOfferingId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_offering_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("session_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassOfferingId");

                    b.ToTable("attendance_sessions");
                });

            modelBuilder.Entity("School_Management_System.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("entity");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("Payload")
                        .HasColumnType("longtext")
                        .HasColumnName("payload");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("School_Management_System.Models.ClassOffering", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long?>("CurriculumId")
                        .HasColumnType("bigint")
                        .HasColumnName("curriculum_id");

                    b.Property<string>("Room")
                        .HasColumnType("longtext")
                        .HasColumnName("room");

                    b.Property<long>("SchoolYearId")
                        .HasColumnType("bigint")
                        .HasColumnName("school_year_id");

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("section_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("subject_id");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("class_offerings");
                });

            modelBuilder.Entity("School_Management_System.Models.ClassSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClassOfferingId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_offering_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("day_of_week");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<long?>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<long?>("TimeSlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("time_slot_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassOfferingId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("class_schedules");
                });

            modelBuilder.Entity("School_Management_System.Models.ClassStudent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClassOfferingId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_offering_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("EnrollmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassOfferingId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("class_students");
                });

            modelBuilder.Entity("School_Management_System.Models.Curriculum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("curricula");
                });

            modelBuilder.Entity("School_Management_System.Models.CurriculumSubject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("CurriculumId")
                        .HasColumnType("bigint")
                        .HasColumnName("curriculum_id");

                    b.Property<long>("GradeLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("grade_level_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_required");

                    b.Property<byte?>("Semester")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("semester");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("subject_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex("SubjectId");

                    b.ToTable("curriculum_subjects");
                });

            modelBuilder.Entity("School_Management_System.Models.Enrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("CurriculumId")
                        .HasColumnType("bigint")
                        .HasColumnName("curriculum_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("enrolled_at");

                    b.Property<long>("GradeLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("grade_level_id");

                    b.Property<long>("SchoolYearId")
                        .HasColumnType("bigint")
                        .HasColumnName("school_year_id");

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("section_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("SectionId");

                    b.HasIndex("StudentId");

                    b.ToTable("enrollments");
                });

            modelBuilder.Entity("School_Management_System.Models.GradeComponent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(6,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("grade_components");
                });

            modelBuilder.Entity("School_Management_System.Models.GradeLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("grade_levels");
                });

            modelBuilder.Entity("School_Management_System.Models.GradingPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long>("SchoolYearId")
                        .HasColumnType("bigint")
                        .HasColumnName("school_year_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("grading_periods");
                });

            modelBuilder.Entity("School_Management_System.Models.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("School_Management_System.Models.SchoolYear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("school_years");
                });

            modelBuilder.Entity("School_Management_System.Models.Section", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AdviserTeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("adviser_teacher_id");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("GradeLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("grade_level_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long>("SchoolYearId")
                        .HasColumnType("bigint")
                        .HasColumnName("school_year_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AdviserTeacherId");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("sections");
                });

            modelBuilder.Entity("School_Management_System.Models.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birthdate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("GuardianContact")
                        .HasColumnType("longtext")
                        .HasColumnName("guardian_contact");

                    b.Property<string>("GuardianName")
                        .HasColumnType("longtext")
                        .HasColumnName("guardian_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Lrn")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lrn");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext")
                        .HasColumnName("middle_name");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("profile_image_url");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext")
                        .HasColumnName("sex");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("students");
                });

            modelBuilder.Entity("School_Management_System.Models.StudentGrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClassOfferingId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_offering_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("GradingPeriodId")
                        .HasColumnType("bigint")
                        .HasColumnName("grading_period_id");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("locked_at");

                    b.Property<decimal?>("PerformanceTasks")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("performance_tasks");

                    b.Property<decimal?>("QuarterGrade")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("quarter_grade");

                    b.Property<decimal?>("QuarterlyAssessment")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("quarterly_assessment");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("WrittenWorks")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("written_works");

                    b.HasKey("Id");

                    b.HasIndex("ClassOfferingId");

                    b.HasIndex("GradingPeriodId");

                    b.HasIndex("StudentId");

                    b.ToTable("student_grades");
                });

            modelBuilder.Entity("School_Management_System.Models.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<long?>("GradeLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("grade_level_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GradeLevelId");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("School_Management_System.Models.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ContactNo")
                        .HasColumnType("longtext")
                        .HasColumnName("contact_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNo")
                        .HasColumnType("longtext")
                        .HasColumnName("employee_no");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("hire_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext")
                        .HasColumnName("middle_name");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("profile_image_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("teachers");
                });

            modelBuilder.Entity("School_Management_System.Models.TimeSlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsBellPeriod")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_bell_period");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("time_slots");
                });

            modelBuilder.Entity("School_Management_System.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("School_Management_System.Models.Announcement", b =>
                {
                    b.HasOne("School_Management_System.Models.ClassOffering", "ClassOffering")
                        .WithMany()
                        .HasForeignKey("ClassOfferingId");

                    b.HasOne("School_Management_System.Models.User", "PostedByUser")
                        .WithMany()
                        .HasForeignKey("PostedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId");

                    b.Navigation("ClassOffering");

                    b.Navigation("PostedByUser");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("School_Management_System.Models.Assessment", b =>
                {
                    b.HasOne("School_Management_System.Models.ClassOffering", "ClassOffering")
                        .WithMany("Assessments")
                        .HasForeignKey("ClassOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.GradeComponent", "Component")
                        .WithMany("Assessments")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.GradingPeriod", "GradingPeriod")
                        .WithMany("Assessments")
                        .HasForeignKey("GradingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassOffering");

                    b.Navigation("Component");

                    b.Navigation("GradingPeriod");
                });

            modelBuilder.Entity("School_Management_System.Models.AssessmentScore", b =>
                {
                    b.HasOne("School_Management_System.Models.Assessment", "Assessment")
                        .WithMany("AssessmentScores")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Student", "Student")
                        .WithMany("AssessmentScores")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("School_Management_System.Models.AttendanceRecord", b =>
                {
                    b.HasOne("School_Management_System.Models.AttendanceSession", "AttendanceSession")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("AttendanceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.User", "MarkedByUser")
                        .WithMany()
                        .HasForeignKey("MarkedByUserId");

                    b.HasOne("School_Management_System.Models.Student", "Student")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceSession");

                    b.Navigation("MarkedByUser");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("School_Management_System.Models.AttendanceSession", b =>
                {
                    b.HasOne("School_Management_System.Models.ClassOffering", "ClassOffering")
                        .WithMany("AttendanceSessions")
                        .HasForeignKey("ClassOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassOffering");
                });

            modelBuilder.Entity("School_Management_System.Models.AuditLog", b =>
                {
                    b.HasOne("School_Management_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("School_Management_System.Models.ClassOffering", b =>
                {
                    b.HasOne("School_Management_System.Models.Curriculum", "Curriculum")
                        .WithMany("ClassOfferings")
                        .HasForeignKey("CurriculumId");

                    b.HasOne("School_Management_System.Models.SchoolYear", "SchoolYear")
                        .WithMany("ClassOfferings")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Section", "Section")
                        .WithMany("ClassOfferings")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Subject", "Subject")
                        .WithMany("ClassOfferings")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Teacher", "Teacher")
                        .WithMany("ClassOfferings")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Curriculum");

                    b.Navigation("SchoolYear");

                    b.Navigation("Section");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("School_Management_System.Models.ClassSchedule", b =>
                {
                    b.HasOne("School_Management_System.Models.ClassOffering", "ClassOffering")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Room", "Room")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("RoomId");

                    b.HasOne("School_Management_System.Models.TimeSlot", "TimeSlot")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("TimeSlotId");

                    b.Navigation("ClassOffering");

                    b.Navigation("Room");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("School_Management_System.Models.ClassStudent", b =>
                {
                    b.HasOne("School_Management_System.Models.ClassOffering", "ClassOffering")
                        .WithMany("ClassStudents")
                        .HasForeignKey("ClassOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Student", "Student")
                        .WithMany("ClassStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassOffering");

                    b.Navigation("Enrollment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("School_Management_System.Models.CurriculumSubject", b =>
                {
                    b.HasOne("School_Management_System.Models.Curriculum", "Curriculum")
                        .WithMany("CurriculumSubjects")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.GradeLevel", "GradeLevel")
                        .WithMany("CurriculumSubjects")
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Subject", "Subject")
                        .WithMany("CurriculumSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("GradeLevel");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("School_Management_System.Models.Enrollment", b =>
                {
                    b.HasOne("School_Management_System.Models.Curriculum", "Curriculum")
                        .WithMany("Enrollments")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.GradeLevel", "GradeLevel")
                        .WithMany("Enrollments")
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.SchoolYear", "SchoolYear")
                        .WithMany("Enrollments")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Section", "Section")
                        .WithMany("Enrollments")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("GradeLevel");

                    b.Navigation("SchoolYear");

                    b.Navigation("Section");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("School_Management_System.Models.GradingPeriod", b =>
                {
                    b.HasOne("School_Management_System.Models.SchoolYear", "SchoolYear")
                        .WithMany("GradingPeriods")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("School_Management_System.Models.Section", b =>
                {
                    b.HasOne("School_Management_System.Models.Teacher", "AdviserTeacher")
                        .WithMany("AdvisorySections")
                        .HasForeignKey("AdviserTeacherId");

                    b.HasOne("School_Management_System.Models.GradeLevel", "GradeLevel")
                        .WithMany("Sections")
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.SchoolYear", "SchoolYear")
                        .WithMany("Sections")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdviserTeacher");

                    b.Navigation("GradeLevel");

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("School_Management_System.Models.Student", b =>
                {
                    b.HasOne("School_Management_System.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("School_Management_System.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("School_Management_System.Models.StudentGrade", b =>
                {
                    b.HasOne("School_Management_System.Models.ClassOffering", "ClassOffering")
                        .WithMany("StudentGrades")
                        .HasForeignKey("ClassOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.GradingPeriod", "GradingPeriod")
                        .WithMany("StudentGrades")
                        .HasForeignKey("GradingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management_System.Models.Student", "Student")
                        .WithMany("StudentGrades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassOffering");

                    b.Navigation("GradingPeriod");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("School_Management_System.Models.Subject", b =>
                {
                    b.HasOne("School_Management_System.Models.GradeLevel", "GradeLevel")
                        .WithMany("Subjects")
                        .HasForeignKey("GradeLevelId");

                    b.Navigation("GradeLevel");
                });

            modelBuilder.Entity("School_Management_System.Models.Teacher", b =>
                {
                    b.HasOne("School_Management_System.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("School_Management_System.Models.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("School_Management_System.Models.Assessment", b =>
                {
                    b.Navigation("AssessmentScores");
                });

            modelBuilder.Entity("School_Management_System.Models.AttendanceSession", b =>
                {
                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("School_Management_System.Models.ClassOffering", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("AttendanceSessions");

                    b.Navigation("ClassSchedules");

                    b.Navigation("ClassStudents");

                    b.Navigation("StudentGrades");
                });

            modelBuilder.Entity("School_Management_System.Models.Curriculum", b =>
                {
                    b.Navigation("ClassOfferings");

                    b.Navigation("CurriculumSubjects");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("School_Management_System.Models.GradeComponent", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("School_Management_System.Models.GradeLevel", b =>
                {
                    b.Navigation("CurriculumSubjects");

                    b.Navigation("Enrollments");

                    b.Navigation("Sections");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("School_Management_System.Models.GradingPeriod", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("StudentGrades");
                });

            modelBuilder.Entity("School_Management_System.Models.Room", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("School_Management_System.Models.SchoolYear", b =>
                {
                    b.Navigation("ClassOfferings");

                    b.Navigation("Enrollments");

                    b.Navigation("GradingPeriods");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("School_Management_System.Models.Section", b =>
                {
                    b.Navigation("ClassOfferings");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("School_Management_System.Models.Student", b =>
                {
                    b.Navigation("AssessmentScores");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("ClassStudents");

                    b.Navigation("Enrollments");

                    b.Navigation("StudentGrades");
                });

            modelBuilder.Entity("School_Management_System.Models.Subject", b =>
                {
                    b.Navigation("ClassOfferings");

                    b.Navigation("CurriculumSubjects");
                });

            modelBuilder.Entity("School_Management_System.Models.Teacher", b =>
                {
                    b.Navigation("AdvisorySections");

                    b.Navigation("ClassOfferings");
                });

            modelBuilder.Entity("School_Management_System.Models.TimeSlot", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("School_Management_System.Models.User", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
